// AUTO-GENERATED by scripts/generate-day-index.mjs — do not edit by hand.
// Regenerated automatically on dev/build/preview/deploy.

import day000 from "./2026-07-07.json";
import day001 from "./2026-07-08.json";
import day002 from "./2026-07-11.json";
import day003 from "./2026-07-12.json";
import day004 from "./2026-07-13.json";
import day005 from "./2026-07-14.json";
import day006 from "./2026-07-15.json";
import day007 from "./2026-07-16.json";
import day008 from "./2026-07-17.json";
import day009 from "./2026-07-18.json";
import day010 from "./2026-07-19.json";
import day011 from "./2026-07-20.json";
import day012 from "./2026-07-21.json";
import day013 from "./2026-07-22.json";
import day014 from "./2026-07-23.json";
import day015 from "./2026-07-24.json";
import day016 from "./2026-07-25.json";
import day017 from "./2026-07-26.json";
import day018 from "./2026-07-27.json";
import day019 from "./2026-07-28.json";
import day020 from "./2026-07-29.json";
import day021 from "./2026-07-30.json";
import day022 from "./2026-07-31.json";
import day023 from "./2026-08-01.json";
import day024 from "./2026-08-02.json";
import day025 from "./2026-08-03.json";
import day026 from "./2026-08-04.json";
import day027 from "./2026-08-05.json";
import day028 from "./2026-08-06.json";
import day029 from "./2026-08-07.json";
import day030 from "./2026-08-08.json";
import day031 from "./2026-08-09.json";
import day032 from "./2026-08-10.json";
import day033 from "./2026-08-11.json";
import day034 from "./2026-08-12.json";
import day035 from "./2026-08-13.json";
import day036 from "./2026-08-14.json";
import day037 from "./2026-08-15.json";
import day038 from "./2026-08-16.json";
import day039 from "./2026-08-17.json";
import day040 from "./2026-08-18.json";
import day041 from "./2026-08-19.json";
import day042 from "./2026-08-20.json";
import day043 from "./2026-08-21.json";
import day044 from "./2026-08-22.json";
import day045 from "./2026-08-23.json";
import day046 from "./2026-08-24.json";
import day047 from "./2026-08-25.json";

export interface RawDayEntry {
  file: string;
  data: unknown;
}

/** Every day report in data/days, sorted by filename (= chronological). */
export const RAW_DAYS: RawDayEntry[] = [
  { file: "2026-07-07.json", data: day000 },
  { file: "2026-07-08.json", data: day001 },
  { file: "2026-07-11.json", data: day002 },
  { file: "2026-07-12.json", data: day003 },
  { file: "2026-07-13.json", data: day004 },
  { file: "2026-07-14.json", data: day005 },
  { file: "2026-07-15.json", data: day006 },
  { file: "2026-07-16.json", data: day007 },
  { file: "2026-07-17.json", data: day008 },
  { file: "2026-07-18.json", data: day009 },
  { file: "2026-07-19.json", data: day010 },
  { file: "2026-07-20.json", data: day011 },
  { file: "2026-07-21.json", data: day012 },
  { file: "2026-07-22.json", data: day013 },
  { file: "2026-07-23.json", data: day014 },
  { file: "2026-07-24.json", data: day015 },
  { file: "2026-07-25.json", data: day016 },
  { file: "2026-07-26.json", data: day017 },
  { file: "2026-07-27.json", data: day018 },
  { file: "2026-07-28.json", data: day019 },
  { file: "2026-07-29.json", data: day020 },
  { file: "2026-07-30.json", data: day021 },
  { file: "2026-07-31.json", data: day022 },
  { file: "2026-08-01.json", data: day023 },
  { file: "2026-08-02.json", data: day024 },
  { file: "2026-08-03.json", data: day025 },
  { file: "2026-08-04.json", data: day026 },
  { file: "2026-08-05.json", data: day027 },
  { file: "2026-08-06.json", data: day028 },
  { file: "2026-08-07.json", data: day029 },
  { file: "2026-08-08.json", data: day030 },
  { file: "2026-08-09.json", data: day031 },
  { file: "2026-08-10.json", data: day032 },
  { file: "2026-08-11.json", data: day033 },
  { file: "2026-08-12.json", data: day034 },
  { file: "2026-08-13.json", data: day035 },
  { file: "2026-08-14.json", data: day036 },
  { file: "2026-08-15.json", data: day037 },
  { file: "2026-08-16.json", data: day038 },
  { file: "2026-08-17.json", data: day039 },
  { file: "2026-08-18.json", data: day040 },
  { file: "2026-08-19.json", data: day041 },
  { file: "2026-08-20.json", data: day042 },
  { file: "2026-08-21.json", data: day043 },
  { file: "2026-08-22.json", data: day044 },
  { file: "2026-08-23.json", data: day045 },
  { file: "2026-08-24.json", data: day046 },
  { file: "2026-08-25.json", data: day047 },
];
